### ISSUE TITLE
conda 4.4 adds "conda activate", "conda deactivate" commands

### ISSUE THREAD

**Issue by anntzer** [esc/conda-zsh-completion#8]
see https://github.com/conda/conda/blob/master/CHANGELOG.md#new-features
completion for the command names (even without the environment names) would be nice.

**Comment by esc** [comment]
fixed by #11

**Comment by diego898** [comment]
I just installed this, but I still can't get activate and deactivate to show up:

![image](https://user-images.githubusercontent.com/742407/54091162-93ee0000-434a-11e9-9f77-19895b3b9579.png)

**Comment by esc** [comment]
@diego898 can you open a new issue for this one? It seems like there are several commands not being picked up.

**Comment by diego898** [comment]
@esc - sure! I opened #14
